### PR TITLE
add links for searching CPAN for XS related code

### PR DESCRIPTION
**Pull request by zmughal**

### CODE REVIEW

**Comment by zmughal** [comment]
That was what I was going to attempt, but I'm not sure if the ElasticSearch setup that they have at MetaCPAN does a suffix search. I can ask on #metacpan.

**Comment by wolfsage** [comment]
Ah good point.

**Comment by wolfsage** [comment]
Thanks

**Comment by rwstauner** [comment]
with metacpan you can search by file mime type (`text/x-c`):
http://tinyurl.com/o2gpom3

**Pull request merged**
